### ISSUE TITLE
I have a problem installing in the linux

### ISSUE THREAD

**Issue by PhoenixAlx** [oTree-org/otree-launcher#2]
I am testing this app, it¡s very insteresting.
I have python  3.4.3 and python 2.7 in the file otree.sh i have changed python to python2.7 but when I run it fail...
The error in log is
****************************************************************

cat ~/.otree-launcher/launcher.log 
Using base prefix '/usr'
New python executable in /MYHOME/.otree-launcher/oTree/bin/python
Installing setuptools, pip...done.
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pip from https://pypi.python.org/packages/py2.py3/p/pip/pip-6.1.1-py2.py3-none-any.whl#md5=172eb5abab25a5e0f7a7b63c7a49378d
  Using cached pip-6.1.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 6.0.8
    Uninstalling pip-6.0.8:
      Successfully uninstalled pip-6.0.8

Successfully installed pip-6.1.1
Processing ./otree_launcher/res/packages/dulwich-0.10.1a.tar.gz
  Requirement already satisfied (use --upgrade to upgrade): dulwich==0.10.1a0 from file:///MYHOME/otree-launcher-master/otree_launcher/res/packages/dulwich-0.10.1a.tar.gz in MYHOME/.otree-launcher/oTree/lib/python3.4/site-packages
Collecting dj-database-url==0.2.2 (from -r /MYHOME/.otree-launcher/temp/requirements_313466024150101672826337043322044670278.txt (line 1))
  Using cached dj-database-url-0.2.2.tar.gz
Collecting gunicorn==18.0 (from -r /MYHOME/.otree-launcher/temp/requirements_313466024150101672826337043322044670278.txt (line 2))
  Using cached gunicorn-18.0-py33-none-any.whl
Collecting static==1.0.2 (from -r /MYHOME/.otree-launcher/temp/requirements_313466024150101672826337043322044670278.txt (line 3))
  Using cached static-1.0.2.tar.gz
Collecting otree-core==0.2.281 (from -r /MYHOME/.otree-launcher/temp/requirements_313466024150101672826337043322044670278.txt (line 4))
  Using cached otree-core-0.2.281.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d0uhs3xw/otree-core

**Comment by oTree-org** [comment]
Thanks for the bug report! Looks like a question for @leliel12.

Until this issue is resolved, you can do the alternative oTree install (which does not use the launcher):

```
git clone git@github.com:oTree-org/oTree.git
pip install -r requirements_base.txt
./otree resetdb
./otree runserver
```

**Comment by PhoenixAlx** [comment]
Thanks. It works changing python by python2.7 and using
git clone https://github.com/oTree-org/oTree

**Comment by leliel12** [comment]
Warning: otree and otree-launcher only works with python 2.7.

2015-04-16 13:25 GMT-03:00 PhoenixAlx <notifications@github.com>:

> Thanks. It works changing python by python2.7 and using
> git clone https://github.com/oTree-org/oTree
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-launcher/issues/2#issuecomment-93777329>
> .
>



-- 
Juan B Cabral

**Comment by PhoenixAlx** [comment]
Leliel12 Yes I know , thank you

**Comment by pank** [comment]
I see the same.  Is there any harm in explicitly calling `python2`.

**Comment by oTree-org** [comment]
Yes that should work. For example you can run: `python2 otree resetdb`. `otree` itself is a Python script equivalent to Django's standard `manage.py`.
